### PR TITLE
Initiate Thumbnail Panel docs.

### PR DESCRIPTION
**Pull request by mathewjordan**
## What does this do?

This seeks to add baseline documentation for the [@iiif/thumbnail-panel](https://github.com/IIIF-Commons/thumbnail-panel/) component. I also updated docusaurus.

 Sections include:

 - Overview
 - Basic Usage (HTML/JS using a web component)
 - React Usage

### CODE REVIEW

**Comment by mathewjordan** [comment]
@edsilv @stephenwf @adamjarling @glenrobson 

Apologies this has taken my awhile to pull together. Any chance for a look today?

If possible, let's iterate towards more advanced issues. Let me know if you see any glaring problems. I'll add a Styling section with a basic example in a followup PR.

**Comment by stephenwf** [comment]
Hi @mathewjordan the docs themselves are automatically added to this repo (to be hosted together on Netlify) but they live inside the `thumbnail-panel` repository itself - keeps everything together an in sync.

So should be able to just copy them to this folder: https://github.com/IIIF-Commons/thumbnail-panel/tree/main/docs

**Comment by stephenwf** [comment]
Here's an example I did to add the stub:
Commit in the thumbnail panel:
https://github.com/IIIF-Commons/thumbnail-panel/commit/6c272950d74011b1c8cf4ee25a55ae58af3c09a8

Commit in the common docs (automatic)
https://github.com/IIIF-Commons/common-docs/commit/5462169c1c9bb21538a954b0e25e3c56549f566c

**Comment by stephenwf** [comment]
I've set up this docusaurus site to work well with symlinks, so if you want a common docs locally, you can do:
```
ln -s ~/github.com/iiif-commons/thumbnail-panel/docs ~/github.com/iiif-commons/common-docs/docs/thumbnail-panel
```

for each of the projects and it should all work (with your own paths)

**Comment by mathewjordan** [comment]
> Hi @mathewjordan the docs themselves are automatically added to this repo (to be hosted together on Netlify) but they live inside the `thumbnail-panel` repository itself - keeps everything together an in sync.
> 
> So should be able to just copy them to this folder: https://github.com/IIIF-Commons/thumbnail-panel/tree/main/docs

I've used MDX for the Overview page. Not necessary, but was hoping to include the component in that. Will this work through the syncing?

**Comment by stephenwf** [comment]
Hmm, that's a fair point. It should work with the syncing if that component exists. I think we probably need to extend the syncing a bit to allow for components to be added (which would be really useful!)

**Comment by stephenwf** [comment]
Alternatively you could commit the components directly to this repo - and just have the md/mdx syncing?

**Comment by adamjarling** [comment]
@mathewjordan @stephenwf So should we ignore this PR?

**Review by adamjarling — APPROVED** [review]
Docs look great, all around and now including Thumbnail Panel!

**Pull request merged**
